Repository 42-webserv/SpaceX, pull requests merged in 2022-12, with the labels that each got.

#6 Dev chunked syntax check part
  syntax/chunked.rfc
  syntax/syntax.cpp
  syntax/syntax.hpp
  syntax/syntax_test_main.cpp
Labels: Priority: ⭑⭑⭑, [Reason] Todo: ⌨, Status: ✅

#12 Dev config add master branch
  .clang-format
  config/config.cpp
  config/config.hpp
  config/config_parse_test.cpp
  config/port_info.cpp
  config/port_info.hpp
  config/spacex_type.cpp
  config/spacex_type.hpp
  config/test.conf
  syntax/chunked.rfc
  syntax/spacex_type.hpp
  syntax/syntax.cpp
  syntax/syntax.hpp
  syntax/syntax_test_main.cpp
Labels: Priority: ⭑⭑, [Reason] Todo: ⌨, Status: ⏸, Status: ✅

#19 Dev main - edit syntax
  Makefile
  config/default.conf
  core/spacex.cpp
  core/spx_config_parse.cpp
  core/spx_config_parse.hpp
  core/spx_config_port_info.cpp
  core/spx_config_port_info.hpp
  core/spx_core_util_box.cpp
  core/spx_kqueue.cpp
  core/spx_socket_init.cpp
  core/spx_socket_init.hpp
Labels: Priority: ⭑, [Reason] Refactor: 🛠

#25 date and connection added
  source/spx_response_generator.cpp
  source/spx_response_generator.hpp
Labels: Priority: ⭑⭑⭑, [Reason] Refactor: 🛠, Status: ✅

#34 response_refactor
  source/spx_response_generator.cpp
  source/spx_response_generator.hpp
Labels: Priority: ⭑⭑⭑, Status: ✅

#43 Issue23
  source/spacex.cpp
  source/spx_response_generator.cpp
  source/spx_response_generator.hpp
Labels: Priority: ⭑⭑⭑, Status: ✅
