Repository 42-webserv/SpaceX, pull requests merged in 2023-01, with the labels that each got.

#54 50 bonus cookie session
  config/default.conf
  config/for_test.conf
  source/spx_client_buffer.cpp
  source/spx_client_buffer.hpp
  source/spx_session_storage.cpp
  source/spx_session_storage.hpp
Labels: Status: ✅

#59 57 autoindex fix
  Makefile_local
  config/default.conf
  data/.DS_Store
  source/spx_autoindex_generator.cpp
Labels: [Reason] Bug: 🐞, Status: ✅

#62 variable fix
  source/spx_client_buffer.cpp
  source/spx_client_buffer.hpp
Labels: Priority: ⭑, [Reason] Refactor: 🛠

#64 Dev cleanup
  config/default.conf
  dev_/test_time_milli.cpp
  source/spx_autoindex_generator.cpp
  source/spx_autoindex_generator.hpp
  source/spx_core_type.hpp
  source/spx_core_util_box.hpp
  source/spx_port_info.cpp
  source/spx_session_storage.cpp
  source/spx_syntax_checker.cpp
Labels: Priority: ⭑⭑⭑, [Reason] Refactor: 🛠, Status: ✅

#75 72 session validate
  data/put_test/multiple_same
  source/spx_client.cpp
  source/spx_client.hpp
  source/spx_kqueue_module.cpp
  source/spx_kqueue_module.hpp
  source/spx_session_storage.cpp
  source/spx_session_storage.hpp
Labels: Priority: ⭑⭑⭑, [Reason] Refactor: 🛠
